name: 'CI Runner ansible deploy-cvp - in main'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'group_vars/*'

jobs:

  run-avd-build:
    runs-on: ubuntu-latest
    container: 
      image: "registry.guzware.net/avd/avd-5.2:v2"

    steps:


#      - name: Install Ansible
#        run: pip install "pyavd[ansible]"

#      - name: Install Arista AVD
#        run: ansible-galaxy collection install arista.avd

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Prod Configurations and Documentation
        run: |
          . /workspace/ansible-venv/bin/activate
          ansible-playbook -i inventory.yml build.yml

      - name: Commit and Push Generated Files
        run: |
          # Make sure any generated files are added to Git
          if [ -d "documentation" ]; then
            git add documentation/
          fi

          if [ -d "intended" ]; then
            git add intended/
          fi

          if [ -d "reports" ]; then
            git add reports/
          fi

          git config user.name "gitea-runner"
          git config user.email "andreas.marqvardsen@gmail.com"
          # Get the current branch name dynamically
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          git commit -s -m "Update generated files from branch $CURRENT_BRANCH" || echo "No changes to commit"

          # Push changes to the current branch
          git push origin $CURRENT_BRANCH



      - name: Deploy changes to CloudVision
        run: |
          . /workspace/ansible-venv/bin/activate 
          ansible-playbook -i inventory.yml deploy-cvp.yml

#      - name: Commit and Push Generated Files
#        run: |
#          # Make sure any generated files are added to Git
#          git add documentation/ intended/
#          git config user.name "Gitea-runner"
#          git config user.email "andreas.marqvardsen@gmail.com"
#          git commit -s -m "Update generated files from Ansible playbook run" || echo "No changes to commit"
#          git push origin main  # Push changes back to the main branch
#        env:
#          GITHUB_TOKEN: ${{ secrets.RUNNER_TOKEN }} 







